/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class CarrayInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CarrayInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CarrayInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_CarrayInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CarrayInt(int nelements) {
    this(libsndfileJNI.new_CarrayInt(nelements), true);
  }

  public int getitem(int index) {
    return libsndfileJNI.CarrayInt_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, int value) {
    libsndfileJNI.CarrayInt_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_int cast() {
    long cPtr = libsndfileJNI.CarrayInt_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static CarrayInt frompointer(SWIGTYPE_p_int t) {
    long cPtr = libsndfileJNI.CarrayInt_frompointer(SWIGTYPE_p_int.getCPtr(t));
    return (cPtr == 0) ? null : new CarrayInt(cPtr, false);
  }

}
