/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class CArrayFloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CArrayFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CArrayFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_CArrayFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public CArrayFloat(int nelements) {
    this(libsndfileJNI.new_CArrayFloat(nelements), true);
  }

  public float getitem(int index) {
    return libsndfileJNI.CArrayFloat_getitem(swigCPtr, this, index);
  }

  public void setitem(int index, float value) {
    libsndfileJNI.CArrayFloat_setitem(swigCPtr, this, index, value);
  }

  public SWIGTYPE_p_float cast() {
    long cPtr = libsndfileJNI.CArrayFloat_cast(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public static CArrayFloat frompointer(SWIGTYPE_p_float t) {
    long cPtr = libsndfileJNI.CArrayFloat_frompointer(SWIGTYPE_p_float.getCPtr(t));
    return (cPtr == 0) ? null : new CArrayFloat(cPtr, false);
  }

}
