/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class libsndfile implements libsndfileConstants {
  public static SWIGTYPE_p_SNDFILE_tag sf_open(String path, int mode, SF_INFO sfinfo) {
    long cPtr = libsndfileJNI.sf_open(path, mode, SF_INFO.getCPtr(sfinfo), sfinfo);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SNDFILE_tag(cPtr, false);
  }

  public static SWIGTYPE_p_SNDFILE_tag sf_open_fd(int fd, int mode, SF_INFO sfinfo, int close_desc) {
    long cPtr = libsndfileJNI.sf_open_fd(fd, mode, SF_INFO.getCPtr(sfinfo), sfinfo, close_desc);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SNDFILE_tag(cPtr, false);
  }

  public static SWIGTYPE_p_SNDFILE_tag sf_open_virtual(SF_VIRTUAL_IO sfvirtual, int mode, SF_INFO sfinfo, SWIGTYPE_p_void user_data) {
    long cPtr = libsndfileJNI.sf_open_virtual(SF_VIRTUAL_IO.getCPtr(sfvirtual), sfvirtual, mode, SF_INFO.getCPtr(sfinfo), sfinfo, SWIGTYPE_p_void.getCPtr(user_data));
    return (cPtr == 0) ? null : new SWIGTYPE_p_SNDFILE_tag(cPtr, false);
  }

  public static int sf_error(SWIGTYPE_p_SNDFILE_tag sndfile) {
    return libsndfileJNI.sf_error(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile));
  }

  public static String sf_strerror(SWIGTYPE_p_SNDFILE_tag sndfile) {
    return libsndfileJNI.sf_strerror(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile));
  }

  public static String sf_error_number(int errnum) {
    return libsndfileJNI.sf_error_number(errnum);
  }

  public static int sf_perror(SWIGTYPE_p_SNDFILE_tag sndfile) {
    return libsndfileJNI.sf_perror(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile));
  }

  public static int sf_error_str(SWIGTYPE_p_SNDFILE_tag sndfile, String str, long len) {
    return libsndfileJNI.sf_error_str(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), str, len);
  }

  public static int sf_command(SWIGTYPE_p_SNDFILE_tag sndfile, int command, SWIGTYPE_p_void data, int datasize) {
    return libsndfileJNI.sf_command(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), command, SWIGTYPE_p_void.getCPtr(data), datasize);
  }

  public static int sf_format_check(SF_INFO info) {
    return libsndfileJNI.sf_format_check(SF_INFO.getCPtr(info), info);
  }

  public static long sf_seek(SWIGTYPE_p_SNDFILE_tag sndfile, long frames, int whence) {
    return libsndfileJNI.sf_seek(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), frames, whence);
  }

  public static int sf_set_string(SWIGTYPE_p_SNDFILE_tag sndfile, int str_type, String str) {
    return libsndfileJNI.sf_set_string(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), str_type, str);
  }

  public static String sf_get_string(SWIGTYPE_p_SNDFILE_tag sndfile, int str_type) {
    return libsndfileJNI.sf_get_string(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), str_type);
  }

  public static String sf_version_string() {
    return libsndfileJNI.sf_version_string();
  }

  public static int sf_current_byterate(SWIGTYPE_p_SNDFILE_tag sndfile) {
    return libsndfileJNI.sf_current_byterate(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile));
  }

  public static long sf_read_raw(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_void ptr, long bytes) {
    return libsndfileJNI.sf_read_raw(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_void.getCPtr(ptr), bytes);
  }

  public static long sf_write_raw(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_void ptr, long bytes) {
    return libsndfileJNI.sf_write_raw(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_void.getCPtr(ptr), bytes);
  }

  public static long sf_readf_short(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_short ptr, long frames) {
    return libsndfileJNI.sf_readf_short(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_short.getCPtr(ptr), frames);
  }

  public static long sf_writef_short(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_short ptr, long frames) {
    return libsndfileJNI.sf_writef_short(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_short.getCPtr(ptr), frames);
  }

  public static long sf_readf_int(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_int ptr, long frames) {
    return libsndfileJNI.sf_readf_int(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_int.getCPtr(ptr), frames);
  }

  public static long sf_writef_int(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_int ptr, long frames) {
    return libsndfileJNI.sf_writef_int(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_int.getCPtr(ptr), frames);
  }

  public static long sf_readf_float(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_float ptr, long frames) {
    return libsndfileJNI.sf_readf_float(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_float.getCPtr(ptr), frames);
  }

  public static long sf_writef_float(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_float ptr, long frames) {
    return libsndfileJNI.sf_writef_float(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_float.getCPtr(ptr), frames);
  }

  public static long sf_readf_double(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_double ptr, long frames) {
    return libsndfileJNI.sf_readf_double(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_double.getCPtr(ptr), frames);
  }

  public static long sf_writef_double(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_double ptr, long frames) {
    return libsndfileJNI.sf_writef_double(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_double.getCPtr(ptr), frames);
  }

  public static long sf_read_short(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_short ptr, long items) {
    return libsndfileJNI.sf_read_short(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_short.getCPtr(ptr), items);
  }

  public static long sf_write_short(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_short ptr, long items) {
    return libsndfileJNI.sf_write_short(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_short.getCPtr(ptr), items);
  }

  public static long sf_read_int(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_int ptr, long items) {
    return libsndfileJNI.sf_read_int(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_int.getCPtr(ptr), items);
  }

  public static long sf_write_int(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_int ptr, long items) {
    return libsndfileJNI.sf_write_int(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_int.getCPtr(ptr), items);
  }

  public static long sf_read_float(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_float ptr, long items) {
    return libsndfileJNI.sf_read_float(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_float.getCPtr(ptr), items);
  }

  public static long sf_write_float(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_float ptr, long items) {
    return libsndfileJNI.sf_write_float(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_float.getCPtr(ptr), items);
  }

  public static long sf_read_double(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_double ptr, long items) {
    return libsndfileJNI.sf_read_double(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_double.getCPtr(ptr), items);
  }

  public static long sf_write_double(SWIGTYPE_p_SNDFILE_tag sndfile, SWIGTYPE_p_double ptr, long items) {
    return libsndfileJNI.sf_write_double(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SWIGTYPE_p_double.getCPtr(ptr), items);
  }

  public static int sf_close(SWIGTYPE_p_SNDFILE_tag sndfile) {
    return libsndfileJNI.sf_close(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile));
  }

  public static void sf_write_sync(SWIGTYPE_p_SNDFILE_tag sndfile) {
    libsndfileJNI.sf_write_sync(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile));
  }

  public static int sf_set_chunk(SWIGTYPE_p_SNDFILE_tag sndfile, SF_CHUNK_INFO chunk_info) {
    return libsndfileJNI.sf_set_chunk(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SF_CHUNK_INFO.getCPtr(chunk_info), chunk_info);
  }

  public static SWIGTYPE_p_SF_CHUNK_ITERATOR sf_get_chunk_iterator(SWIGTYPE_p_SNDFILE_tag sndfile, SF_CHUNK_INFO chunk_info) {
    long cPtr = libsndfileJNI.sf_get_chunk_iterator(SWIGTYPE_p_SNDFILE_tag.getCPtr(sndfile), SF_CHUNK_INFO.getCPtr(chunk_info), chunk_info);
    return (cPtr == 0) ? null : new SWIGTYPE_p_SF_CHUNK_ITERATOR(cPtr, false);
  }

  public static SWIGTYPE_p_SF_CHUNK_ITERATOR sf_next_chunk_iterator(SWIGTYPE_p_SF_CHUNK_ITERATOR iterator) {
    long cPtr = libsndfileJNI.sf_next_chunk_iterator(SWIGTYPE_p_SF_CHUNK_ITERATOR.getCPtr(iterator));
    return (cPtr == 0) ? null : new SWIGTYPE_p_SF_CHUNK_ITERATOR(cPtr, false);
  }

  public static int sf_get_chunk_size(SWIGTYPE_p_SF_CHUNK_ITERATOR it, SF_CHUNK_INFO chunk_info) {
    return libsndfileJNI.sf_get_chunk_size(SWIGTYPE_p_SF_CHUNK_ITERATOR.getCPtr(it), SF_CHUNK_INFO.getCPtr(chunk_info), chunk_info);
  }

  public static int sf_get_chunk_data(SWIGTYPE_p_SF_CHUNK_ITERATOR it, SF_CHUNK_INFO chunk_info) {
    return libsndfileJNI.sf_get_chunk_data(SWIGTYPE_p_SF_CHUNK_ITERATOR.getCPtr(it), SF_CHUNK_INFO.getCPtr(chunk_info), chunk_info);
  }

}
