/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public interface libsndfileConstants {
  public final static int SEEK_SET = 0;
  public final static int SEEK_CUR = 1;
  public final static int SEEK_END = 2;
  public final static int SF_FORMAT_WAV = 0x010000;
  public final static int SF_FORMAT_AIFF = 0x020000;
  public final static int SF_FORMAT_AU = 0x030000;
  public final static int SF_FORMAT_RAW = 0x040000;
  public final static int SF_FORMAT_PAF = 0x050000;
  public final static int SF_FORMAT_SVX = 0x060000;
  public final static int SF_FORMAT_NIST = 0x070000;
  public final static int SF_FORMAT_VOC = 0x080000;
  public final static int SF_FORMAT_IRCAM = 0x0A0000;
  public final static int SF_FORMAT_W64 = 0x0B0000;
  public final static int SF_FORMAT_MAT4 = 0x0C0000;
  public final static int SF_FORMAT_MAT5 = 0x0D0000;
  public final static int SF_FORMAT_PVF = 0x0E0000;
  public final static int SF_FORMAT_XI = 0x0F0000;
  public final static int SF_FORMAT_HTK = 0x100000;
  public final static int SF_FORMAT_SDS = 0x110000;
  public final static int SF_FORMAT_AVR = 0x120000;
  public final static int SF_FORMAT_WAVEX = 0x130000;
  public final static int SF_FORMAT_SD2 = 0x160000;
  public final static int SF_FORMAT_FLAC = 0x170000;
  public final static int SF_FORMAT_CAF = 0x180000;
  public final static int SF_FORMAT_WVE = 0x190000;
  public final static int SF_FORMAT_OGG = 0x200000;
  public final static int SF_FORMAT_MPC2K = 0x210000;
  public final static int SF_FORMAT_RF64 = 0x220000;
  public final static int SF_FORMAT_PCM_S8 = 0x0001;
  public final static int SF_FORMAT_PCM_16 = 0x0002;
  public final static int SF_FORMAT_PCM_24 = 0x0003;
  public final static int SF_FORMAT_PCM_32 = 0x0004;
  public final static int SF_FORMAT_PCM_U8 = 0x0005;
  public final static int SF_FORMAT_FLOAT = 0x0006;
  public final static int SF_FORMAT_DOUBLE = 0x0007;
  public final static int SF_FORMAT_ULAW = 0x0010;
  public final static int SF_FORMAT_ALAW = 0x0011;
  public final static int SF_FORMAT_IMA_ADPCM = 0x0012;
  public final static int SF_FORMAT_MS_ADPCM = 0x0013;
  public final static int SF_FORMAT_GSM610 = 0x0020;
  public final static int SF_FORMAT_VOX_ADPCM = 0x0021;
  public final static int SF_FORMAT_G721_32 = 0x0030;
  public final static int SF_FORMAT_G723_24 = 0x0031;
  public final static int SF_FORMAT_G723_40 = 0x0032;
  public final static int SF_FORMAT_DWVW_12 = 0x0040;
  public final static int SF_FORMAT_DWVW_16 = 0x0041;
  public final static int SF_FORMAT_DWVW_24 = 0x0042;
  public final static int SF_FORMAT_DWVW_N = 0x0043;
  public final static int SF_FORMAT_DPCM_8 = 0x0050;
  public final static int SF_FORMAT_DPCM_16 = 0x0051;
  public final static int SF_FORMAT_VORBIS = 0x0060;
  public final static int SF_FORMAT_ALAC_16 = 0x0070;
  public final static int SF_FORMAT_ALAC_20 = 0x0071;
  public final static int SF_FORMAT_ALAC_24 = 0x0072;
  public final static int SF_FORMAT_ALAC_32 = 0x0073;
  public final static int SF_ENDIAN_FILE = 0x00000000;
  public final static int SF_ENDIAN_LITTLE = 0x10000000;
  public final static int SF_ENDIAN_BIG = 0x20000000;
  public final static int SF_ENDIAN_CPU = 0x30000000;
  public final static int SF_FORMAT_SUBMASK = 0x0000FFFF;
  public final static int SF_FORMAT_TYPEMASK = 0x0FFF0000;
  public final static int SF_FORMAT_ENDMASK = 0x30000000;

  public final static int SFC_GET_LIB_VERSION = 0x1000;
  public final static int SFC_GET_LOG_INFO = 0x1001;
  public final static int SFC_GET_CURRENT_SF_INFO = 0x1002;
  public final static int SFC_GET_NORM_DOUBLE = 0x1010;
  public final static int SFC_GET_NORM_FLOAT = 0x1011;
  public final static int SFC_SET_NORM_DOUBLE = 0x1012;
  public final static int SFC_SET_NORM_FLOAT = 0x1013;
  public final static int SFC_SET_SCALE_FLOAT_INT_READ = 0x1014;
  public final static int SFC_SET_SCALE_INT_FLOAT_WRITE = 0x1015;
  public final static int SFC_GET_SIMPLE_FORMAT_COUNT = 0x1020;
  public final static int SFC_GET_SIMPLE_FORMAT = 0x1021;
  public final static int SFC_GET_FORMAT_INFO = 0x1028;
  public final static int SFC_GET_FORMAT_MAJOR_COUNT = 0x1030;
  public final static int SFC_GET_FORMAT_MAJOR = 0x1031;
  public final static int SFC_GET_FORMAT_SUBTYPE_COUNT = 0x1032;
  public final static int SFC_GET_FORMAT_SUBTYPE = 0x1033;
  public final static int SFC_CALC_SIGNAL_MAX = 0x1040;
  public final static int SFC_CALC_NORM_SIGNAL_MAX = 0x1041;
  public final static int SFC_CALC_MAX_ALL_CHANNELS = 0x1042;
  public final static int SFC_CALC_NORM_MAX_ALL_CHANNELS = 0x1043;
  public final static int SFC_GET_SIGNAL_MAX = 0x1044;
  public final static int SFC_GET_MAX_ALL_CHANNELS = 0x1045;
  public final static int SFC_SET_ADD_PEAK_CHUNK = 0x1050;
  public final static int SFC_SET_ADD_HEADER_PAD_CHUNK = 0x1051;
  public final static int SFC_UPDATE_HEADER_NOW = 0x1060;
  public final static int SFC_SET_UPDATE_HEADER_AUTO = 0x1061;
  public final static int SFC_FILE_TRUNCATE = 0x1080;
  public final static int SFC_SET_RAW_START_OFFSET = 0x1090;
  public final static int SFC_SET_DITHER_ON_WRITE = 0x10A0;
  public final static int SFC_SET_DITHER_ON_READ = 0x10A1;
  public final static int SFC_GET_DITHER_INFO_COUNT = 0x10A2;
  public final static int SFC_GET_DITHER_INFO = 0x10A3;
  public final static int SFC_GET_EMBED_FILE_INFO = 0x10B0;
  public final static int SFC_SET_CLIPPING = 0x10C0;
  public final static int SFC_GET_CLIPPING = 0x10C1;
  public final static int SFC_GET_INSTRUMENT = 0x10D0;
  public final static int SFC_SET_INSTRUMENT = 0x10D1;
  public final static int SFC_GET_LOOP_INFO = 0x10E0;
  public final static int SFC_GET_BROADCAST_INFO = 0x10F0;
  public final static int SFC_SET_BROADCAST_INFO = 0x10F1;
  public final static int SFC_GET_CHANNEL_MAP_INFO = 0x1100;
  public final static int SFC_SET_CHANNEL_MAP_INFO = 0x1101;
  public final static int SFC_RAW_DATA_NEEDS_ENDSWAP = 0x1110;
  public final static int SFC_WAVEX_SET_AMBISONIC = 0x1200;
  public final static int SFC_WAVEX_GET_AMBISONIC = 0x1201;
  public final static int SFC_SET_VBR_ENCODING_QUALITY = 0x1300;
  public final static int SFC_SET_COMPRESSION_LEVEL = 0x1301;
  public final static int SFC_SET_CART_INFO = 0x1400;
  public final static int SFC_GET_CART_INFO = 0x1401;
  public final static int SFC_TEST_IEEE_FLOAT_REPLACE = 0x6001;
  public final static int SFC_SET_ADD_DITHER_ON_WRITE = 0x1070;
  public final static int SFC_SET_ADD_DITHER_ON_READ = 0x1071;

  public final static int SF_STR_TITLE = 0x01;
  public final static int SF_STR_COPYRIGHT = 0x02;
  public final static int SF_STR_SOFTWARE = 0x03;
  public final static int SF_STR_ARTIST = 0x04;
  public final static int SF_STR_COMMENT = 0x05;
  public final static int SF_STR_DATE = 0x06;
  public final static int SF_STR_ALBUM = 0x07;
  public final static int SF_STR_LICENSE = 0x08;
  public final static int SF_STR_TRACKNUMBER = 0x09;
  public final static int SF_STR_GENRE = 0x10;

  public final static int SF_FALSE = 0;
  public final static int SF_TRUE = 1;
  public final static int SFM_READ = 0x10;
  public final static int SFM_WRITE = 0x20;
  public final static int SFM_RDWR = 0x30;
  public final static int SF_AMBISONIC_NONE = 0x40;
  public final static int SF_AMBISONIC_B_FORMAT = 0x41;

  public final static int SF_ERR_NO_ERROR = 0;
  public final static int SF_ERR_UNRECOGNISED_FORMAT = 1;
  public final static int SF_ERR_SYSTEM = 2;
  public final static int SF_ERR_MALFORMED_FILE = 3;
  public final static int SF_ERR_UNSUPPORTED_ENCODING = 4;

  public final static int SF_CHANNEL_MAP_INVALID = 0;
  public final static int SF_CHANNEL_MAP_MONO = 1;
  public final static int SF_CHANNEL_MAP_LEFT = SF_CHANNEL_MAP_MONO + 1;
  public final static int SF_CHANNEL_MAP_RIGHT = SF_CHANNEL_MAP_LEFT + 1;
  public final static int SF_CHANNEL_MAP_CENTER = SF_CHANNEL_MAP_RIGHT + 1;
  public final static int SF_CHANNEL_MAP_FRONT_LEFT = SF_CHANNEL_MAP_CENTER + 1;
  public final static int SF_CHANNEL_MAP_FRONT_RIGHT = SF_CHANNEL_MAP_FRONT_LEFT + 1;
  public final static int SF_CHANNEL_MAP_FRONT_CENTER = SF_CHANNEL_MAP_FRONT_RIGHT + 1;
  public final static int SF_CHANNEL_MAP_REAR_CENTER = SF_CHANNEL_MAP_FRONT_CENTER + 1;
  public final static int SF_CHANNEL_MAP_REAR_LEFT = SF_CHANNEL_MAP_REAR_CENTER + 1;
  public final static int SF_CHANNEL_MAP_REAR_RIGHT = SF_CHANNEL_MAP_REAR_LEFT + 1;
  public final static int SF_CHANNEL_MAP_LFE = SF_CHANNEL_MAP_REAR_RIGHT + 1;
  public final static int SF_CHANNEL_MAP_FRONT_LEFT_OF_CENTER = SF_CHANNEL_MAP_LFE + 1;
  public final static int SF_CHANNEL_MAP_FRONT_RIGHT_OF_CENTER = SF_CHANNEL_MAP_FRONT_LEFT_OF_CENTER + 1;
  public final static int SF_CHANNEL_MAP_SIDE_LEFT = SF_CHANNEL_MAP_FRONT_RIGHT_OF_CENTER + 1;
  public final static int SF_CHANNEL_MAP_SIDE_RIGHT = SF_CHANNEL_MAP_SIDE_LEFT + 1;
  public final static int SF_CHANNEL_MAP_TOP_CENTER = SF_CHANNEL_MAP_SIDE_RIGHT + 1;
  public final static int SF_CHANNEL_MAP_TOP_FRONT_LEFT = SF_CHANNEL_MAP_TOP_CENTER + 1;
  public final static int SF_CHANNEL_MAP_TOP_FRONT_RIGHT = SF_CHANNEL_MAP_TOP_FRONT_LEFT + 1;
  public final static int SF_CHANNEL_MAP_TOP_FRONT_CENTER = SF_CHANNEL_MAP_TOP_FRONT_RIGHT + 1;
  public final static int SF_CHANNEL_MAP_TOP_REAR_LEFT = SF_CHANNEL_MAP_TOP_FRONT_CENTER + 1;
  public final static int SF_CHANNEL_MAP_TOP_REAR_RIGHT = SF_CHANNEL_MAP_TOP_REAR_LEFT + 1;
  public final static int SF_CHANNEL_MAP_TOP_REAR_CENTER = SF_CHANNEL_MAP_TOP_REAR_RIGHT + 1;
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_W = SF_CHANNEL_MAP_TOP_REAR_CENTER + 1;
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_X = SF_CHANNEL_MAP_AMBISONIC_B_W + 1;
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_Y = SF_CHANNEL_MAP_AMBISONIC_B_X + 1;
  public final static int SF_CHANNEL_MAP_AMBISONIC_B_Z = SF_CHANNEL_MAP_AMBISONIC_B_Y + 1;
  public final static int SF_CHANNEL_MAP_MAX = SF_CHANNEL_MAP_AMBISONIC_B_Z + 1;

  public final static long SF_COUNT_MAX = 0x7FFFFFFFFFFFFFFFL;
  public final static int SFD_DEFAULT_LEVEL = 0;
  public final static int SFD_CUSTOM_LEVEL = 0x40000000;
  public final static int SFD_NO_DITHER = 500;
  public final static int SFD_WHITE = 501;
  public final static int SFD_TRIANGULAR_PDF = 502;

  public final static int SF_LOOP_NONE = 800;
  public final static int SF_LOOP_FORWARD = SF_LOOP_NONE + 1;
  public final static int SF_LOOP_BACKWARD = SF_LOOP_FORWARD + 1;
  public final static int SF_LOOP_ALTERNATING = SF_LOOP_BACKWARD + 1;

  public final static int SF_SEEK_SET = 0;
  public final static int SF_SEEK_CUR = 1;
  public final static int SF_SEEK_END = 2;

}
