/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_BROADCAST_INFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_BROADCAST_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_BROADCAST_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_BROADCAST_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDescription(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_description_set(swigCPtr, this, value);
  }

  public String getDescription() {
    return libsndfileJNI.SF_BROADCAST_INFO_description_get(swigCPtr, this);
  }

  public void setOriginator(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_originator_set(swigCPtr, this, value);
  }

  public String getOriginator() {
    return libsndfileJNI.SF_BROADCAST_INFO_originator_get(swigCPtr, this);
  }

  public void setOriginator_reference(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_originator_reference_set(swigCPtr, this, value);
  }

  public String getOriginator_reference() {
    return libsndfileJNI.SF_BROADCAST_INFO_originator_reference_get(swigCPtr, this);
  }

  public void setOrigination_date(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_origination_date_set(swigCPtr, this, value);
  }

  public String getOrigination_date() {
    return libsndfileJNI.SF_BROADCAST_INFO_origination_date_get(swigCPtr, this);
  }

  public void setOrigination_time(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_origination_time_set(swigCPtr, this, value);
  }

  public String getOrigination_time() {
    return libsndfileJNI.SF_BROADCAST_INFO_origination_time_get(swigCPtr, this);
  }

  public void setTime_reference_low(long value) {
    libsndfileJNI.SF_BROADCAST_INFO_time_reference_low_set(swigCPtr, this, value);
  }

  public long getTime_reference_low() {
    return libsndfileJNI.SF_BROADCAST_INFO_time_reference_low_get(swigCPtr, this);
  }

  public void setTime_reference_high(long value) {
    libsndfileJNI.SF_BROADCAST_INFO_time_reference_high_set(swigCPtr, this, value);
  }

  public long getTime_reference_high() {
    return libsndfileJNI.SF_BROADCAST_INFO_time_reference_high_get(swigCPtr, this);
  }

  public void setVersion(short value) {
    libsndfileJNI.SF_BROADCAST_INFO_version_set(swigCPtr, this, value);
  }

  public short getVersion() {
    return libsndfileJNI.SF_BROADCAST_INFO_version_get(swigCPtr, this);
  }

  public void setUmid(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_umid_set(swigCPtr, this, value);
  }

  public String getUmid() {
    return libsndfileJNI.SF_BROADCAST_INFO_umid_get(swigCPtr, this);
  }

  public void setReserved(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_reserved_set(swigCPtr, this, value);
  }

  public String getReserved() {
    return libsndfileJNI.SF_BROADCAST_INFO_reserved_get(swigCPtr, this);
  }

  public void setCoding_history_size(long value) {
    libsndfileJNI.SF_BROADCAST_INFO_coding_history_size_set(swigCPtr, this, value);
  }

  public long getCoding_history_size() {
    return libsndfileJNI.SF_BROADCAST_INFO_coding_history_size_get(swigCPtr, this);
  }

  public void setCoding_history(String value) {
    libsndfileJNI.SF_BROADCAST_INFO_coding_history_set(swigCPtr, this, value);
  }

  public String getCoding_history() {
    return libsndfileJNI.SF_BROADCAST_INFO_coding_history_get(swigCPtr, this);
  }

  public SF_BROADCAST_INFO() {
    this(libsndfileJNI.new_SF_BROADCAST_INFO(), true);
  }

}
