/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_CHUNK_INFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_CHUNK_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_CHUNK_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_CHUNK_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(String value) {
    libsndfileJNI.SF_CHUNK_INFO_id_set(swigCPtr, this, value);
  }

  public String getId() {
    return libsndfileJNI.SF_CHUNK_INFO_id_get(swigCPtr, this);
  }

  public void setId_size(long value) {
    libsndfileJNI.SF_CHUNK_INFO_id_size_set(swigCPtr, this, value);
  }

  public long getId_size() {
    return libsndfileJNI.SF_CHUNK_INFO_id_size_get(swigCPtr, this);
  }

  public void setDatalen(long value) {
    libsndfileJNI.SF_CHUNK_INFO_datalen_set(swigCPtr, this, value);
  }

  public long getDatalen() {
    return libsndfileJNI.SF_CHUNK_INFO_datalen_get(swigCPtr, this);
  }

  public void setData(SWIGTYPE_p_void value) {
    libsndfileJNI.SF_CHUNK_INFO_data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = libsndfileJNI.SF_CHUNK_INFO_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SF_CHUNK_INFO() {
    this(libsndfileJNI.new_SF_CHUNK_INFO(), true);
  }

}
