/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_CART_INFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_CART_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_CART_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_CART_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setVersion(String value) {
    libsndfileJNI.SF_CART_INFO_version_set(swigCPtr, this, value);
  }

  public String getVersion() {
    return libsndfileJNI.SF_CART_INFO_version_get(swigCPtr, this);
  }

  public void setTitle(String value) {
    libsndfileJNI.SF_CART_INFO_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return libsndfileJNI.SF_CART_INFO_title_get(swigCPtr, this);
  }

  public void setArtist(String value) {
    libsndfileJNI.SF_CART_INFO_artist_set(swigCPtr, this, value);
  }

  public String getArtist() {
    return libsndfileJNI.SF_CART_INFO_artist_get(swigCPtr, this);
  }

  public void setCut_id(String value) {
    libsndfileJNI.SF_CART_INFO_cut_id_set(swigCPtr, this, value);
  }

  public String getCut_id() {
    return libsndfileJNI.SF_CART_INFO_cut_id_get(swigCPtr, this);
  }

  public void setClient_id(String value) {
    libsndfileJNI.SF_CART_INFO_client_id_set(swigCPtr, this, value);
  }

  public String getClient_id() {
    return libsndfileJNI.SF_CART_INFO_client_id_get(swigCPtr, this);
  }

  public void setCategory(String value) {
    libsndfileJNI.SF_CART_INFO_category_set(swigCPtr, this, value);
  }

  public String getCategory() {
    return libsndfileJNI.SF_CART_INFO_category_get(swigCPtr, this);
  }

  public void setClassification(String value) {
    libsndfileJNI.SF_CART_INFO_classification_set(swigCPtr, this, value);
  }

  public String getClassification() {
    return libsndfileJNI.SF_CART_INFO_classification_get(swigCPtr, this);
  }

  public void setOut_cue(String value) {
    libsndfileJNI.SF_CART_INFO_out_cue_set(swigCPtr, this, value);
  }

  public String getOut_cue() {
    return libsndfileJNI.SF_CART_INFO_out_cue_get(swigCPtr, this);
  }

  public void setStart_date(String value) {
    libsndfileJNI.SF_CART_INFO_start_date_set(swigCPtr, this, value);
  }

  public String getStart_date() {
    return libsndfileJNI.SF_CART_INFO_start_date_get(swigCPtr, this);
  }

  public void setStart_time(String value) {
    libsndfileJNI.SF_CART_INFO_start_time_set(swigCPtr, this, value);
  }

  public String getStart_time() {
    return libsndfileJNI.SF_CART_INFO_start_time_get(swigCPtr, this);
  }

  public void setEnd_date(String value) {
    libsndfileJNI.SF_CART_INFO_end_date_set(swigCPtr, this, value);
  }

  public String getEnd_date() {
    return libsndfileJNI.SF_CART_INFO_end_date_get(swigCPtr, this);
  }

  public void setEnd_time(String value) {
    libsndfileJNI.SF_CART_INFO_end_time_set(swigCPtr, this, value);
  }

  public String getEnd_time() {
    return libsndfileJNI.SF_CART_INFO_end_time_get(swigCPtr, this);
  }

  public void setProducer_app_id(String value) {
    libsndfileJNI.SF_CART_INFO_producer_app_id_set(swigCPtr, this, value);
  }

  public String getProducer_app_id() {
    return libsndfileJNI.SF_CART_INFO_producer_app_id_get(swigCPtr, this);
  }

  public void setProducer_app_version(String value) {
    libsndfileJNI.SF_CART_INFO_producer_app_version_set(swigCPtr, this, value);
  }

  public String getProducer_app_version() {
    return libsndfileJNI.SF_CART_INFO_producer_app_version_get(swigCPtr, this);
  }

  public void setUser_def(String value) {
    libsndfileJNI.SF_CART_INFO_user_def_set(swigCPtr, this, value);
  }

  public String getUser_def() {
    return libsndfileJNI.SF_CART_INFO_user_def_get(swigCPtr, this);
  }

  public void setLevel_reference(int value) {
    libsndfileJNI.SF_CART_INFO_level_reference_set(swigCPtr, this, value);
  }

  public int getLevel_reference() {
    return libsndfileJNI.SF_CART_INFO_level_reference_get(swigCPtr, this);
  }

  public void setPost_timers(SF_CART_TIMER value) {
    libsndfileJNI.SF_CART_INFO_post_timers_set(swigCPtr, this, SF_CART_TIMER.getCPtr(value), value);
  }

  public SF_CART_TIMER getPost_timers() {
    long cPtr = libsndfileJNI.SF_CART_INFO_post_timers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SF_CART_TIMER(cPtr, false);
  }

  public void setReserved(String value) {
    libsndfileJNI.SF_CART_INFO_reserved_set(swigCPtr, this, value);
  }

  public String getReserved() {
    return libsndfileJNI.SF_CART_INFO_reserved_get(swigCPtr, this);
  }

  public void setUrl(String value) {
    libsndfileJNI.SF_CART_INFO_url_set(swigCPtr, this, value);
  }

  public String getUrl() {
    return libsndfileJNI.SF_CART_INFO_url_get(swigCPtr, this);
  }

  public void setTag_text_size(long value) {
    libsndfileJNI.SF_CART_INFO_tag_text_size_set(swigCPtr, this, value);
  }

  public long getTag_text_size() {
    return libsndfileJNI.SF_CART_INFO_tag_text_size_get(swigCPtr, this);
  }

  public void setTag_text(String value) {
    libsndfileJNI.SF_CART_INFO_tag_text_set(swigCPtr, this, value);
  }

  public String getTag_text() {
    return libsndfileJNI.SF_CART_INFO_tag_text_get(swigCPtr, this);
  }

  public SF_CART_INFO() {
    this(libsndfileJNI.new_SF_CART_INFO(), true);
  }

}
