/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_FORMAT_INFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_FORMAT_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_FORMAT_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_FORMAT_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFormat(int value) {
    libsndfileJNI.SF_FORMAT_INFO_format_set(swigCPtr, this, value);
  }

  public int getFormat() {
    return libsndfileJNI.SF_FORMAT_INFO_format_get(swigCPtr, this);
  }

  public void setName(String value) {
    libsndfileJNI.SF_FORMAT_INFO_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return libsndfileJNI.SF_FORMAT_INFO_name_get(swigCPtr, this);
  }

  public void setExtension(String value) {
    libsndfileJNI.SF_FORMAT_INFO_extension_set(swigCPtr, this, value);
  }

  public String getExtension() {
    return libsndfileJNI.SF_FORMAT_INFO_extension_get(swigCPtr, this);
  }

  public SF_FORMAT_INFO() {
    this(libsndfileJNI.new_SF_FORMAT_INFO(), true);
  }

}
