/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_INFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFrames(long value) {
    libsndfileJNI.SF_INFO_frames_set(swigCPtr, this, value);
  }

  public long getFrames() {
    return libsndfileJNI.SF_INFO_frames_get(swigCPtr, this);
  }

  public void setSamplerate(int value) {
    libsndfileJNI.SF_INFO_samplerate_set(swigCPtr, this, value);
  }

  public int getSamplerate() {
    return libsndfileJNI.SF_INFO_samplerate_get(swigCPtr, this);
  }

  public void setChannels(int value) {
    libsndfileJNI.SF_INFO_channels_set(swigCPtr, this, value);
  }

  public int getChannels() {
    return libsndfileJNI.SF_INFO_channels_get(swigCPtr, this);
  }

  public void setFormat(int value) {
    libsndfileJNI.SF_INFO_format_set(swigCPtr, this, value);
  }

  public int getFormat() {
    return libsndfileJNI.SF_INFO_format_get(swigCPtr, this);
  }

  public void setSections(int value) {
    libsndfileJNI.SF_INFO_sections_set(swigCPtr, this, value);
  }

  public int getSections() {
    return libsndfileJNI.SF_INFO_sections_get(swigCPtr, this);
  }

  public void setSeekable(int value) {
    libsndfileJNI.SF_INFO_seekable_set(swigCPtr, this, value);
  }

  public int getSeekable() {
    return libsndfileJNI.SF_INFO_seekable_get(swigCPtr, this);
  }

  public SF_INFO() {
    this(libsndfileJNI.new_SF_INFO(), true);
  }

}
