/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_INSTRUMENT_loops {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_INSTRUMENT_loops(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_INSTRUMENT_loops obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_INSTRUMENT_loops(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMode(int value) {
    libsndfileJNI.SF_INSTRUMENT_loops_mode_set(swigCPtr, this, value);
  }

  public int getMode() {
    return libsndfileJNI.SF_INSTRUMENT_loops_mode_get(swigCPtr, this);
  }

  public void setStart(long value) {
    libsndfileJNI.SF_INSTRUMENT_loops_start_set(swigCPtr, this, value);
  }

  public long getStart() {
    return libsndfileJNI.SF_INSTRUMENT_loops_start_get(swigCPtr, this);
  }

  public void setEnd(long value) {
    libsndfileJNI.SF_INSTRUMENT_loops_end_set(swigCPtr, this, value);
  }

  public long getEnd() {
    return libsndfileJNI.SF_INSTRUMENT_loops_end_get(swigCPtr, this);
  }

  public void setCount(long value) {
    libsndfileJNI.SF_INSTRUMENT_loops_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return libsndfileJNI.SF_INSTRUMENT_loops_count_get(swigCPtr, this);
  }

  public SF_INSTRUMENT_loops() {
    this(libsndfileJNI.new_SF_INSTRUMENT_loops(), true);
  }

}
