/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_INSTRUMENT {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_INSTRUMENT(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_INSTRUMENT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_INSTRUMENT(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGain(int value) {
    libsndfileJNI.SF_INSTRUMENT_gain_set(swigCPtr, this, value);
  }

  public int getGain() {
    return libsndfileJNI.SF_INSTRUMENT_gain_get(swigCPtr, this);
  }

  public void setBasenote(char value) {
    libsndfileJNI.SF_INSTRUMENT_basenote_set(swigCPtr, this, value);
  }

  public char getBasenote() {
    return libsndfileJNI.SF_INSTRUMENT_basenote_get(swigCPtr, this);
  }

  public void setDetune(char value) {
    libsndfileJNI.SF_INSTRUMENT_detune_set(swigCPtr, this, value);
  }

  public char getDetune() {
    return libsndfileJNI.SF_INSTRUMENT_detune_get(swigCPtr, this);
  }

  public void setVelocity_lo(char value) {
    libsndfileJNI.SF_INSTRUMENT_velocity_lo_set(swigCPtr, this, value);
  }

  public char getVelocity_lo() {
    return libsndfileJNI.SF_INSTRUMENT_velocity_lo_get(swigCPtr, this);
  }

  public void setVelocity_hi(char value) {
    libsndfileJNI.SF_INSTRUMENT_velocity_hi_set(swigCPtr, this, value);
  }

  public char getVelocity_hi() {
    return libsndfileJNI.SF_INSTRUMENT_velocity_hi_get(swigCPtr, this);
  }

  public void setKey_lo(char value) {
    libsndfileJNI.SF_INSTRUMENT_key_lo_set(swigCPtr, this, value);
  }

  public char getKey_lo() {
    return libsndfileJNI.SF_INSTRUMENT_key_lo_get(swigCPtr, this);
  }

  public void setKey_hi(char value) {
    libsndfileJNI.SF_INSTRUMENT_key_hi_set(swigCPtr, this, value);
  }

  public char getKey_hi() {
    return libsndfileJNI.SF_INSTRUMENT_key_hi_get(swigCPtr, this);
  }

  public void setLoop_count(int value) {
    libsndfileJNI.SF_INSTRUMENT_loop_count_set(swigCPtr, this, value);
  }

  public int getLoop_count() {
    return libsndfileJNI.SF_INSTRUMENT_loop_count_get(swigCPtr, this);
  }

  public SF_INSTRUMENT_loops getLoops() {
    long cPtr = libsndfileJNI.SF_INSTRUMENT_loops_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SF_INSTRUMENT_loops(cPtr, false);
  }

  public SF_INSTRUMENT() {
    this(libsndfileJNI.new_SF_INSTRUMENT(), true);
  }

}
