/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SF_LOOP_INFO {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SF_LOOP_INFO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SF_LOOP_INFO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        libsndfileJNI.delete_SF_LOOP_INFO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTime_sig_num(short value) {
    libsndfileJNI.SF_LOOP_INFO_time_sig_num_set(swigCPtr, this, value);
  }

  public short getTime_sig_num() {
    return libsndfileJNI.SF_LOOP_INFO_time_sig_num_get(swigCPtr, this);
  }

  public void setTime_sig_den(short value) {
    libsndfileJNI.SF_LOOP_INFO_time_sig_den_set(swigCPtr, this, value);
  }

  public short getTime_sig_den() {
    return libsndfileJNI.SF_LOOP_INFO_time_sig_den_get(swigCPtr, this);
  }

  public void setLoop_mode(int value) {
    libsndfileJNI.SF_LOOP_INFO_loop_mode_set(swigCPtr, this, value);
  }

  public int getLoop_mode() {
    return libsndfileJNI.SF_LOOP_INFO_loop_mode_get(swigCPtr, this);
  }

  public void setNum_beats(int value) {
    libsndfileJNI.SF_LOOP_INFO_num_beats_set(swigCPtr, this, value);
  }

  public int getNum_beats() {
    return libsndfileJNI.SF_LOOP_INFO_num_beats_get(swigCPtr, this);
  }

  public void setBpm(float value) {
    libsndfileJNI.SF_LOOP_INFO_bpm_set(swigCPtr, this, value);
  }

  public float getBpm() {
    return libsndfileJNI.SF_LOOP_INFO_bpm_get(swigCPtr, this);
  }

  public void setRoot_key(int value) {
    libsndfileJNI.SF_LOOP_INFO_root_key_set(swigCPtr, this, value);
  }

  public int getRoot_key() {
    return libsndfileJNI.SF_LOOP_INFO_root_key_get(swigCPtr, this);
  }

  public void setFuture(SWIGTYPE_p_int value) {
    libsndfileJNI.SF_LOOP_INFO_future_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getFuture() {
    long cPtr = libsndfileJNI.SF_LOOP_INFO_future_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public SF_LOOP_INFO() {
    this(libsndfileJNI.new_SF_LOOP_INFO(), true);
  }

}
