/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.meganerd.sndfile;

public class SWIGTYPE_p_f_p_q_const__void_long_long_p_void__long_long {
  private long swigCPtr;

  protected SWIGTYPE_p_f_p_q_const__void_long_long_p_void__long_long(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_q_const__void_long_long_p_void__long_long() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_q_const__void_long_long_p_void__long_long obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

